// export const ADD_PRODUCT = "ADD_PRODUCT";
// export const SET_PRODUCT = "SET_PRODUCT";
export const UPLOAD_PRODUCT_FORM_START = "UPLOAD_PRODUCT_FORM_START";
export const UPLOAD_PRODUCT_FORM_FAIL = "UPLOAD_PRODUCT_FORM_FAIL";
export const UPLOAD_PRODUCT_FORM_SUCCESS = "UPLOAD_PRODUCT_FORM_SUCCESS";

export const UPLOAD_PRODUCT_IMAGE_START = "UPLOAD_PRODUCT_IMAGE_START";
export const UPLOAD_PRODUCT_IMAGE_SUCCESS = "UPLOAD_PRODUCT_IMAGE_SUCCESS";
export const UPLOAD_PRODUCT_IMAGE_FAIL = "UPLOAD_PRODUCT_IMAGE_FAIL";

export const DELETE_PRODUCT_IMAGE_START = "DELETE_PRODUCT_IMAGE_START";
export const DELETE_PRODUCT_IMAGE_SUCCESS = "DELETE_PRODUCT_IMAGE_SUCCESS";
export const DELETE_PRODUCT_IMAGE_FAIL = "DELETE_PRODUCT_IMAGE_FAIL";

//------CART-----------
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const INCREASE_SINGLE_PROD_COUNT = "INCREASE_SINGLE_PROD_COUNT";
export const DECREASE_SINGLE_PROD_COUNT = "DECREASE_SINGLE_PROD_COUNT";
export const DELETE_PROD_IN_CART = "DELETE_PROD_IN_CART";
//------CART-----------
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
